### ISSUE TITLE
Zero Modes

### ISSUE THREAD

**Issue by HippoSock** [MonsieurV/py-findpeaks#2]
It's probably also quite important to note that some of these methods fail when trying to analyse a number of niche cases, for example consider zero modes: these modes usually have a 0 frequency component which does not form a full peak, but forms a half peak which is bounded by the end of the set of data, something which most algorithms are not able to detect. 

Also +1 for the good overview.

**Comment by MonsieurV** [comment]
Yeah, sure, they are pretty good algorithms for the common cases, but clearly don't do any magic. [No Silver Bullet](http://worrydream.com/refs/Brooks-NoSilverBullet.pdf) as they say!

Do you have sample data to illustrate zero modes signal?

We can do a review of algorithms that works in some special edge cases. :)

Anyway, thanks for the feedback.

Peace.
