### ISSUE TITLE
now about mlpy.findpeaks?

### ISSUE THREAD

**Issue by svilendobrev** [MonsieurV/py-findpeaks#5]
how do they compare?
from mlpy import findpeaks_dist, findpeaks_win 
i need replacement for the window one as mlpy seems harder-and-harder to install and use (latest 3.5.0 is from 2012)

**Comment by MonsieurV** [comment]
Hi @svilendobrev 

You are speaking of [this module](http://mlpy.sourceforge.net/)?

I will add them to the comparative.
http://mlpy.sourceforge.net/docs/3.5/findpeaks.html

**Comment by svilendobrev** [comment]
yes, that is the mlpy one.

**Comment by MonsieurV** [comment]
@svilendobrev [here](https://github.com/MonsieurV/py-findpeaks#mlpyfindpeaks_dist) you go

Tell me if there is any more complete comment to add on these functions.

And thanks for the report!
